routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resources([
    'getCampaign' => 'CampaignController',
    'getUser' => 'UserController',
    'getPlasma' => 'BplasmaController',
    'getPartner' => 'PartnerController',
    'getContacts' => 'MessageController',
    'getGallery' => 'GalleryController',
    'getGalleryImage' => 'GalleryImageController',
]);
Route::get('/bloodsearch','SearchController@index');
Route::get('/plasma','PlasmaController@index');
Route::get('/registerplasma','RegisterController@index');
Route::post('/plasmaapplyForm', 'PlasmaController@store')->name('apply');
Route::get('/getPlace/{id}','PlasmaController@getPlace')->name('getPlace');
Route::get('/getInfo/{id}','PlasmaController@getInfo')->name('getInfo');
Route::get('/getLocation/{id}','RegisterController@getLocation')->name('getLocation');
Route::get('/contact','FormController@index');
Route::post('/contactform','FormController@store');
Route::get('/getFields/{id}','SearchController@getFields')->name('getFields');
Route::get('/getData/{id}','SearchController@getData')->name('getData');
Route::get('/', 'MainController@index');
Route::get('/event/{id}', 'MainController@show')->name('event.profile');
Route::get('/about-us', 'FrontEnd\MembersController@index');
Route::get('/events','FrontEnd\EventsController@index');
Route::get('/getFields1/{id}','DataController@getFields1')->name('getFields1');
Route::get('/form', function () {
    return view('frontEnd.apply');
});
Route::get('/user/{id}', 'TimesController@apply')->name('getUser.apply');
Route::post('/applyForm1', 'TimesController@applyForm');
Route::get('getGalleryImage/{id}', array('as' => 'show_album', 'uses' => 'GalleryImageController@show'));
Route::get('addimage/{id}', array('as' => 'add_image', 'uses' => 'GalleryImageController@create'));

Route::get('gallery', 'FrontEnd\GalleryController@gallery');

Route::get('gallery/{id}', 'FrontEnd\GalleryController@single_gallery')->name('gsingle');

Auth::routes([
    'register' => true,
    'reset' => false
]);
Route::get('/chart', 'HomeController@index');
Route::get('admin', 'HomeController@index');
Route::post('/applyForm', 'MainController@store')->name('apply');
Route::get('/home', 'HomeController@index')->name('home');
// Route::get('toast', 'HomeController@toast')->name('toast');

app/HomeSlider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HomeSlider extends Model
{

  protected $fillable = ['name', 'description','organizer','venue','date','phone','time', 'image'];

}

resources/views/admin/home-slider/edit.blade.php
@extends('admin.layouts.master')

@section('contents')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Edit Campaign Details</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ url('admin') }}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{{ url('getCampaign') }}">Campaign</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- Horizontal Form -->
                        <div class="card card-info">
                            <div class="card-header">
                                <h3 class="card-title">Donation Campaign Form</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form class="form-horizontal" method="POST"
                                  action="{{route('getCampaign.update', $slider->id)}}" method="post"
                                  enctype="multipart/form-data" class="form-horizontal">
                                {{ csrf_field() }}
                                {{method_field('PUT')}}
                                <div class="card-body">
                                    <small>
                                        <ul>
                                            {!! implode('', $errors->all('<li style="color:red">:message</li>')) !!}
                                        </ul>
                                    </small>
                                    <div class="form-group row">
                                        <label for="name" class="col-sm-2 col-form-label">Name</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="name" name="name"
                                                   value="{{ $slider->name }}"
                                                   placeholder="Name">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="description" class="col-sm-2 col-form-label">Description</label>
                                        <div class="col-sm-10">
                                            <textarea type="text" class="form-control" id="description"
                                                      name="description" placeholder="Description">
                                                {!! $slider->description !!}</textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="oname" class="col-sm-2 col-form-label">Organizer Name</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="oname" name="oname"
                                                   value="{{ $slider->organizer }}"
                                                   placeholder="Organizer Name">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="vname" class="col-sm-2 col-form-label"> Venue Name</label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="vname" name="vname"
                                                   value="{{ $slider->venue }}"
                                                   placeholder="Venue Name">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="date" class="col-sm-2 col-form-label">Date</label>
                                        <div class="col-sm-10">
                                            <input type="date" class="form-control" id="date" name="date"
                                                   value="{{ $slider->date }}"
                                                   placeholder="Date">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="phone" class="col-sm-2 col-form-label">Phone </label>
                                        <div class="col-sm-10">
                                            <input type="tel" class="form-control" id="phone" name="phone"
                                                   placeholder="9812345678" pattern="[9]{1}[0-9]{9}"
                                                   value="{{$slider->phone}}" required>
                                            <small class="form-text text-muted">
                                                Format: 9812345678</small>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="phone" class="col-sm-2 col-form-label">Phone </label>
                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="time" name="time"
                                                   placeholder="3PM -5PM"
                                                   value="{{$slider->time}}" required>
                                            <small class="form-text text-muted">
                                                Format: 3PM -5PM</small>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="image" class="col-sm-2 col-form-label">Image</label>
                                        <div class=" col-sm-10">
                                            <img src="{{url('images/sliders')}}/{{$slider->image}}" height="80px"
                                                 alt="Slider Image"
                                                 title="Image Slider">
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" class="custom-file-input" id="image"
                                                           name="image">
                                                    <label class="custom-file-label" for="image">Choose file</label>
                                                </div>
                                                <div class="input-group-append">
                                                    <span class="input-group-text" id="">Upload</span>
                                                </div>
                                            </div>

                                            <ul>{!! implode('', $errors->all('<li style="color:red">:message</li>')) !!}</ul>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-info">Submit</button>
                                    <button type="reset" class="btn btn-default float-right">Reset</button>
                                    <button type="button" class="btn btn-default float-right" title="Edit"
                                            onclick="location.href='{{url()->previous()}}'">
                                        Cancel
                                    </button>
                                </div>
                                <!-- /.card-footer -->
                            </form>
                        </div>
                        <!-- /.card -->

                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>

    <!-- /.content-wrapper -->

@endsection
@section('js')
    <script>
        $(function () {
            $('#description').summernote()
        })
    </script>
    <script type="application/javascript">
        $('input[type="file"]').change(function(e){
            var fileName = e.target.files[0].name;
            $('.custom-file-label').html(fileName);
        });
    </script>
@endsection

resources/views/admin/home-slider/homeslider.blade.php
@extends('admin.layouts.master')

@section('css')

    <style>
        .view-page {
            font-size: 60%;
        }
        .view-page:hover{
            text-decoration: underline;
        }
    </style>
@endsection

@section('contents')


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">DONATION CAMPAIGNS
                            <a href="/" class="view-page">(View Page)</a>
                        </h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ url('admin') }}">Home</a></li>
                            <li class="breadcrumb-item">DONATION CAMPAIGNS</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title float-left">Donation Campaigns Table</h3>
                                <button type="button" class="btn btn-success float-right"
                                        onclick="location.href='{{route('getCampaign.create')}}';">
                                    <i class="fa fa-plus"> Add New </i>
                                </button>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="table" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>S.N.</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Image</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($sliders as $slider)
                                        <tr>
                                            <td></td>
                                            <td>{{ $slider->name }}</td>
                                            <td>{!! $slider->description !!}</td>
                                            <td><img src="{{url('images/sliders')}}/{{$slider->image}}" height="80px"
                                                     alt="Image" title="Slider {{ $slider->name }}"></td>
                                            <td>
                                                <button type="button" class="btn btn-primary" title="Edit"
                                                        onclick="location.href='{{route('getCampaign.edit',$slider->id)}}';">
                                                    <i class="fas fa-edit"></i></button>
                                                <button type="button" class="btn btn-warning" title="View"
                                                        data-toggle="modal" data-target="#viewModal{{$slider->id}}">
                                                    <i class="fas fa-eye"></i></button>
                                                <button type="submit" class="btn btn-danger" title="Remove"
                                                        data-toggle="modal" data-target="#delModal{{$slider->id}}">
                                                    <i class="fas fa-trash"></i></button>
                                            </td>
                                        </tr>
                                        <!-- View Modal -->
                                        <div class="modal fade" id="viewModal{{$slider->id}}" role="dialog">
                                            <div class="modal-dialog">

                                                <!-- Modal content-->
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title">
                                                            Donor Campaign {{$slider->id}} {{ $slider->name }}</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <img src="{{url('images/sliders')}}/{{$slider->image}}"
                                                             height="80px" alt="Image"
                                                             title="{{$slider->image}}">
                                                        <p>Name: {{ $slider->name }}</p>
                                                        <p>Organizer Name: {{ $slider->organizer }}</p>
                                                        <p>Venue Name: {{ $slider->venue }}</p>
                                                        <p>Date: {{ $slider->date }}</p>
                                                        <p>Phone: {{ $slider->phone }}</p>
                                                        <p>Time: {{ $slider->time }}</p>
                                                        <p>Description : {!! $slider->description !!}</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button class="btn btn-danger btn-default pull-left"
                                                                data-dismiss="modal">Close
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Delete Modal -->
                                        <div class="modal fade" id="delModal{{$slider->id}}" role="dialog">
                                            <div class="modal-dialog">

                                                <!-- Modal content-->
                                                <div class="modal-content">
                                                    <div class="modal-header">

                                                        <h4 class="modal-title">Donor Campaign Deletion </h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Are you sure to delete the campaign
                                                            '<strong>{{$slider->id}} {{ $slider->name }}</strong>' ?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button class="btn btn-danger btn-default pull-left"
                                                                data-dismiss="modal">Close
                                                        </button>
                                                        <form action="{{route('getCampaign.destroy', $slider->id)}}"
                                                              method="POST">
                                                            {{method_field('DELETE')}}
                                                            {{ csrf_field() }}
                                                            <button type="submit" class="btn btn-danger">Delete</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                        <th>S.N.</th>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Image</th>
                                        <th>Actions</th>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
        <!-- /.content -->
    </div>

    <!-- /.content-wrapper -->

@endsection